### ISSUE TITLE
http_test.ts

### ISSUE THREAD

**Issue by wangtxxl** [denoland/net#1]
chrome is ok but curl and  firefox never response 
```sh
./deno_osx_x64 --version
deno: 0.1.12
v8: 7.1.302.4
typescript: 3.1.6
```
```ts
import { serve } from "https://deno.land/x/net/http.ts";

const addr = "127.0.0.1:8090";
const s = serve(addr);
console.log(`listening on http://${addr}/`);

const body = (new TextEncoder()).encode("Hello World\n");


async function main() {
  for await (const req of s) {
  await req.respond({ status: 200, body });
  }
}

main();
```

```sh
curl http://127.0.0.1:8090/
curl: (56) Recv failure: Connection reset by peer
```

**Comment by alexhultman** [comment]
Works in Firefox for me. Does not work in curl or wrk for me.

**Comment by FrankFang** [comment]
It works in Chrome for me, but not in curl.

**Comment by justjavac** [comment]
This server may only accept one link from a user agent.

1. `deno http_test.ts -D`

	```
	...
	listening on http://0.0.0.0:8000/
	Deno requests network access to "listen". Grant? [yN] y
	DEBUG RS - msg_from_js Listen sync true
	DEBUG RS - resource lookup 3
	DEBUG RS - msg_from_js Accept sync false
	```

2. open Chrome, visit

	```
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 0 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Read sync false
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 0 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Write sync false
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Read sync false
	DEBUG RS - loop process - 1 events, 0.000s
	```

3. refresh it

	```
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 0 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Write sync false
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Read sync false
	DEBUG RS - loop process - 1 events, 0.000s
	```

4. open Firefox, visit 

	```
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 0 events, 0.000s
	```

	The program is suspended.

5. refresh the webpage in Chrome again

	```
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 0 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Write sync false
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - msg_from_js Read sync false
	DEBUG RS - loop process - 1 events, 0.000s
	```

	It still works.

6. Waiting for a long time


	```
	DEBUG RS - loop process - 1 events, 0.000s
	DEBUG RS - resource lookup 4
	DEBUG RS - dropping I/O source: 1
	DEBUG RS - loop process - 0 events, 0.000s
	DEBUG RS - msg_from_js Close sync true
	ConnectionAborted: 你的主机中的软件中止了一个已建立的连接。 (os error 10053)
		at maybeError (deno/js/errors.ts:38:12)
		at handleAsyncMsgFromRust (deno/js/dispatch.ts:27:17)
	```

My system is Chinese, so the error message is also Chinese. I don't know what the English information is. I will simply translate it:

> 你的主机中的软件中止了一个已建立的连接。
>
> The software in your host has aborted an established connection.

**Comment by justjavac** [comment]
When using a browser to access, 2 requests were sent at the same time

```
GET / HTTP/1.1
GET /favicon.ico HTTP/1.1
```

![](https://user-images.githubusercontent.com/359395/49128907-64ba0280-f308-11e8-8e04-17ad52cc20d4.png)

For some reason (probably a bug), deno has not received `EOF`, cause Conn to not close. When using curl, can always receive `EOF`, so [c.close()](https://github.com/denoland/net/blob/0c8ad6eb1af05b259cc7c622e87e27b402886c96/http.ts#L36) has been invoked.

**Comment by FrankFang** [comment]
@justjavac try `curl http://127.0.0.1:8090/favicon.ico & curl http://127.0.0.1:8090/`

**Comment by justjavac** [comment]
I add some log-code,  in Chrome, [c.close()](https://github.com/denoland/net/blob/0c8ad6eb1af05b259cc7c622e87e27b402886c96/http.ts#L36) has indeed **NOT** been invoked, and [listener.accept()](https://github.com/denoland/net/blob/0c8ad6eb1af05b259cc7c622e87e27b402886c96/http.ts#L10) has **NOT** been invoked too.

Maybe Chrome uses a socket connection pool, both requests use the same socket.

I generate a [NetLog dump file](https://github.com/denoland/net/files/2623424/chrome-net-export.log).

url `http://127.0.0.1:8000`:

```
...
t=1007 [st=0]     +SOCKET_POOL  [dt=1]
t=1008 [st=1]        SOCKET_POOL_BOUND_TO_CONNECT_JOB
                     --> source_dependency = 55197 (TRANSPORT_CONNECT_JOB)
t=1008 [st=1]        SOCKET_POOL_BOUND_TO_SOCKET
                     --> source_dependency = 55198 (SOCKET)
...
```

url `http://127.0.0.1:8000//favicon.ico`:

```
t=1064 [st=0]     +SOCKET_POOL  [dt=0]
t=1064 [st=0]        SOCKET_POOL_REUSED_AN_EXISTING_SOCKET  <--- HERE
                     --> idle_ms = 53
t=1064 [st=0]        SOCKET_POOL_BOUND_TO_SOCKET
                     --> source_dependency = 55198 (SOCKET)
```

**SOCKET_POOL_REUSED_AN_EXISTING_SOCKET**.

------------

I tried `curl -H  'Connection: keep-alive'`, but there is no such error like Chrome.

**Comment by zhmushan** [comment]
@justjavac u are right.
when i use browser access the url, the connection cannot be closed properly.

the following code seems to be working fine
```ts
import { serveConn } from './net/http'
import { listen } from 'deno'
;(async () => {
  const addr = '0.0.0.0:8000'
  const listener = listen('tcp', addr)
  console.log('listening on', addr)
  while (true) {
    const conn = await listener.accept()
    const res = await serveConn(conn).next()
    await res.value.respond({ body: new TextEncoder().encode('Hello\n') })
    conn.close()
  }
})()
```

**Comment by ry** [comment]
Hey - sorry for the late reply to this. `http.ts` is only half-implemented, as you can tell. It needs someone (probably me) to dig in and complete it. Help welcome - but otherwise you'll have to wait a few weeks. Ultimately we'll probably use a native http parser - this was added so we can benchmark what sort of overhead parsing in pure JS has.
